const inputField = document.getElementById('input-field')

console.log(inputField)

//document.getElementById('clear').addEventListener('click', () => inputField.value = inputField.value.slice(1,))
document.getElementById('clear').addEventListener('click', () => inputField.value = '')
//document.getElementById('mc')
document.getElementById('percentage').addEventListener('click', () => inputField.value += '%')
document.getElementById('divide').addEventListener('click', () => inputField.value += '/')
document.getElementById('seven').addEventListener('click', () => inputField.value += '7')
document.getElementById('eight').addEventListener('click', () => inputField.value += '8')
document.getElementById('nine').addEventListener('click', () => inputField.value += '9')
document.getElementById('multiply').addEventListener('click', () => inputField.value += '*')
document.getElementById('four').addEventListener('click', () => inputField.value += '4')
document.getElementById('five').addEventListener('click', () => inputField.value += '5')
document.getElementById('six').addEventListener('click', () => inputField.value += '6')
document.getElementById('minus').addEventListener('click', () => inputField.value += '-')
document.getElementById('one').addEventListener('click', () => inputField.value += '1')
document.getElementById('two').addEventListener('click', () => inputField.value += '2')
document.getElementById('three').addEventListener('click', () => inputField.value += '3')
document.getElementById('dot').addEventListener('click', () => inputField.value += '.')
document.getElementById('add').addEventListener('click', () => inputField.value += '+')
document.getElementById('zero').addEventListener('click', () => inputField.value += '0')
document.getElementById('equalto').addEventListener('click', () => inputField.value = eval(inputField.value))

